config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'products#index'

  resources :products
  resources :wishes do
    get :get_wish_products
  end

  post '/add_product', to: 'wishes#add_product'
  delete '/remove_product', to: 'wishes#remove_product'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :whish_products
  has_many :wishes, through: :whish_products

  has_one_attached :image

  validates :product_name, presence: true
  validates :price, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_wishes, foreign_key: :sender_id, class_name: 'Wish'
  has_many :received_wishes, foreign_key: :receiver_id, class_name: 'Wish'

  enum user_type: { user: 0, admin: 1 }

  validates :user_type, presence: true
  validates :user_name, presence: true, length: { minimum: 2, maximum: 15 }, uniqueness: true
  validates :password, presence: true, length: { minimum: 10 }
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: :sender_id

  belongs_to :followings, class_name: "User", optional: true, foreign_key: :receiver_id
  has_many :wish_products
  has_many :products, through: :wish_products

  enum status: { pending: 0, completed: 1 }

end

app/models/wish_product.rb
class WishProduct < ApplicationRecord
  belongs_to :wish
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @products = @products.where("product_name LIKE ?", "#{params[:search_params]}%") if params[:search_params].present?
  
    @products = @products.where('price >= ?', params[:min_price]) if params[:min_price].present?
    
    @products = @products.where('price <= ?', params[:max_price]) if params[:max_price].present?
  
    @products = @products.where('price <= ?', '500') if params[:under_500] == '1'
  
    @products = @products.where('price >= ? AND price <= ?', '500', '1000') if params[:between_500_1000] == '1'
    @products = @products.where('price >= ? AND price <= ?', '1000', '5000') if params[:between_1000_5000] == '1'
  end
  
  
  def show
    @wish = Wish.last
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = product.find(params[:id])
    @product.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def product_params
      params.require(:product).permit(:price, :product_name, :description, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    def index
      @user = User.all
    end
  
    def show
      @user = User.find(params[:id])
    end
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to @user
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
      @user = User.find(params[:id])
    end
  
    def update
      @user = User.find(params[:id])
  
      if @user.update(user_params)
        redirect_to @user
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @user = User.find(params[:id])
      @user.destroy
  
      redirect_to root_path, status: :see_other
    end
  
    private
      def user_params
        params.require(:user).permit(:email, :user_name, :password, :user_type)
      end  
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  
  def index
    @wish = Wish.last
  end

  def show
    @wish = Wish.find(params[:id])
  end

  def new
    @wish = Wish.new
  end

  def create
    create_wish
  end

  def edit
    @wish = Wish.find(params[:id])
  end

  def update
    @wish = Wish.find(params[:id])

    if @wish.update(wish_params)
      redirect_to @wish
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy

    redirect_to root_path, status: :see_other
  end

  def add_product
    @wish = Wish.last
    if @wish.present?
      WishProduct.create(product_id: params[:id],  wish_id: @wish.id )
      respond_to do |format|
        format.js { render layout: false, content_type: 'text/javascript' }
      end
    else
      create_wish
      WishProduct.create(product_id: params[:wish][:product_id], wish_id: @wish.id )
      respond_to do |format|
        format.js { render js: "alert('not able to add product to wish');" }
      end
    end
  end


  def remove_product
    @product = Product.find_by_id(params[:id])
    @wish = Wish.last
  
    if @product.present?
      @wish.products.delete(@product)
      respond_to do |format|
        format.js { render layout: false, content_type: 'text/javascript' }
      end
    else
      respond_to do |format|
        format.js { render js: "alert('Product or wish not found');" }
      end
    end
  end
  

  def get_wish_products
    @wish.products
  end

  # def send_wish_to_user
  #   @wish.products
  # end

  private
  
    def create_wish
      @wish = Wish.new(sender_id: 1)
      @wish.status = "pending"
      @wish.save
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MakeAWish</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/products/_product.html.erb
    <%= link_to product_path(product), class: 'text-decoration-none text-dark' do %>
      <% if product.image.attached? %>
        <picture>
          <%= image_tag url_for(product.image), alt: product.product_name, class: 'img-fluid img-thumbnail'%>
        </picture>
      <% end %>
      <div>
        <h5 class="card-title"><%= product.product_name %></h5>
        <h5 class="card-title"><%= product.price %></h5>
      </div>
    <% end %>

app/views/products/_select.html.erb
  <select name="cars" id="cars" class="form-select mt-3">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
  </select>

app/views/products/index.html.erb
<div style ='overflow-x: hidden;'> 
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid ">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a href="/" class="btn btn-primary mr-2">Home</a>
          </li>
          <li class="nav-item">
            <a href="/wishes" class="btn btn-primary mr-2">My Wish</a>
          </li>

          <li class="nav-item">
            <a href="" class="btn btn-primary mr-2">My profile</a>
          </li>

          <li class="nav-item">
            <a href="/products/new" class="btn btn-primary mr-2">Create Product</a>
          </li>
        
        </ul>

        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  

  <div class="row">
    <div class="col-4">
      <div id="list-example" class="list-group">
        <%= form_with(url: products_path, method: :get, class: "form-row") do |form| %>

          <div class="col-md-4 mb-3">
            <%= form.label :max_price, "Max Price" %>
            <%= form.number_field :max_price, class: "form-control", placeholder: "Max Price" %>
          </div>

          <div class="col-md-4 mb-3">
            <%= form.label :min_price, "Min Price" %>
            <%= form.number_field :min_price, class: "form-control", placeholder: "Min Price" %>
          </div>

          <div class="col-md-4 mb-3">
            <%= form.label :under_500, "Under 500" %>
            <%= form.check_box :under_500, class: "form-check-input" %>
          </div>

          <div class="col-md-4 mb-3">
            <%= form.label :between_500_1000, "500-1000" %>
            <%= form.check_box :between_500_1000, class: "form-check-input" %>
          </div>

          <div class="col-md-4 mb-3">
            <%= form.label :between_1000_5000, "1000-5000" %>
            <%= form.check_box :between_1000_5000, class: "form-check-input" %>
          </div>

          <div class="col-md-12">
            <%= form.submit "Filter", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
    

    <div class="col-8">
        <h1>Products</h1>
        <ul class="list-group">
          <% @products.each do |product| %>
            <%= render partial: 'product', locals: { product: product } %>
          <% end %>
        </ul>
    </div>
  </div>

  <footer>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-end">
        <li class="page-item disabled">
          <a class="page-link">Previous</a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
          <a class="page-link" href="#">Next</a>
        </li>
      </ul>
    </nav>
  </<footer>>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :product_name %><br>
    <%= form.text_field :product_name %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :product_image %><br>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path%>

app/views/products/show.html.erb
<div class="row" style="overflow-x: hidden;">
  <div class="col-md-6 col-lg-4 mb-4">
    <div class="card h-100">
      <div class="card-body">
        <%= render partial: 'product', locals: { product: @product } %>
        <p class="card-text"><%= @product.description %></p>
        <%= render partial: 'select' %>
      </div>
      <% if not @wish.products.include?(@product) %>
        <%= button_to 'Add Product', 
                      add_product_path(id: @product.id), 
                      method: :post, 
                      remote: true, 
                      data: { controller: "wish", action: "click->wish#addProduct" }, 
                      class: "btn btn-primary btn-block" %>
      <% end %>

    </div>
  </div>
</div>

app/views/wishes/_buttons.html.erb
<div class="card-footer">
  <% if products.include?(product) %>
        <%= button_to 'Remove Product', 
                      remove_product_path(id: product.id), 
                      method: :delete, 
                      remote: true, 
                      data: { controller: "wish", action: "click->wish#removeProduct" }, 
                      class: "btn btn-primary btn-block" %>

  <% else %>
      <%= button_to 'Remove Product', 
                      add_product_path(id: product.id), 
                      method: :post, 
                      remote: true, 
                      data: { controller: "wish", action: "click->wish#addProduct" }, 
                      class: "btn btn-primary btn-block" %>
  <% end %>
</div>

app/views/wishes/index.html.erb
<div class="row" style="overflow-x: hidden;">
  <h1>My wish</h1>
  <% @wish.products.each do |product| %>
    <div class="col-md-6 col-lg-4 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <%= render partial: 'products/product', locals: { product: product } %>
          <p class="card-text"><%= product.description %></p>
          <%= render partial: 'products/select' %>
        </div>
        <%= render partial: 'buttons', locals: { products: @wish.products, product: product } %>
      </div>
    </div>
  <% end %>
</div>

app/views/wishes/new.html.erb
<h1>New wish</h1>

<%= form_with model: @wish do |form| %>
  <div>
    <%= form.label :sender_id %><br>
    <%= form.text_field :sender_id %>
  </div>

  <div>
    <%= form.label :receiver_id %><br>
    <%= form.text_area :receiver_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wishes/show.html.erb
<h1>Add product to your wish</h1>
<% @wish.products.each do |product| %>
  <div>
    <div><%= product.product_name %></div>
    <% if @wish.wish_products.include?(product) %>
      <button data-controller="wish" data-action="click->wish#addToWishlist" data-wish-id="<%= @wish.id %>" data-product-id="<%= product.id %>">
        Remove Product
      </button>
    <% else %>
      <button data-controller="wish" data-action="click->wish#removeFromWishlist" data-wish-id="<%= @wish.id %>" data-product-id="<%= product.id %>">
        Add Product
      </button>
    <% end %>
  </div>
<% end %>